import { Toaster } from "react-hot-toast";
import Header from "./_component/Header";
import "./globals.css";


export const metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Toaster toastOptions={{ duration: 1000 }} />
        {children}
      </body>
    </html>
  );
}
