import React from 'react'


export const metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
}

//static -- dynamic

//server component
export default function Page() {
  return (
    <div>

      <h1 className='text-zinc-800 font-bold text-2xl'>hello jee next js</h1>

    </div>
  )
}

