import React from 'react'


export const generateMetadata = async ({ params }) => {
  const { id } = await params;
  return {
    title: `Post-${id}`,
    description: 'Generated by create next app',
  }
}

export default async function Page({ params }) {

  const { id } = await params;

  return (
    <div>

      <h1>This is Single Post Page</h1>

    </div>
  )
}
