import axios from 'axios';
import React from 'react'


export const generateMetadata = async ({ params }) => {
  const { id } = await params;
  return {
    title: `Post-${id}`,
    description: 'Generated by create next app',
  }
}

export default async function Page({ params }) {

  const { id } = await params;
  const data = await axios.get(`https://67831c8c8b6c7a1316f382b3.mockapi.io/posts/${id}`);

  return (
    <div>

      <h1>This is Single Post Page</h1>

    </div>
  )
}
